Repository shunyaek/minimal.css, pull requests merged in 2020-06, with the labels that each got.

#7 Styling <table>s and responsive features.
  example.html
  minimal.css
Labels: enhancement

#6 Image Styling
  example.html
  minimal.css
Labels: enhancement

#12 Fixed h1 offset
  minimal.css
Labels: bug

#14 Implemented image borders
  minimal.css
Labels: bug, enhancement
